# action.yml
name: "Restart K8S deployment"
description: "Greet someone and record the time"
inputs:
  tag:  # id of input
    description: "Tag version of docker"
    required: true
    default: "default"
  deployment-dir:
    description: "Deployment directory of the repo"
    required: true
  image:
    description: "Image docker name"
    required: true
  token:
    description: "Token for managing github repo"
    required: true
outputs:
  digest:
    description: "just here for now"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.tag }}
    - ${{ inputs.deployment-dir }}
    - ${{ inputs.image }}
    - ${{ inputs.token }}
