# action.yml
name: "Restart K8S deployment"
description: "Greet someone and record the time"
inputs:
  namespace:  # id of input
    description: "Which namespace"
    required: true
    default: "default"
  server-url:
    description: "server url"
    required: true
  token:
    description: "token to authenticate to the cluster"
    required: true
  deployment:
    description: "deployment name"
    required: true
  image-name:
    description: "docker image name to update to"
    required: false
  container-name:
    description: "container name inside pod to update"
    required: false
outputs:
  digest:
    description: "just here for now"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.server-url }}
    - ${{ inputs.token }}
    - ${{ inputs.deployment }}
    - ${{ inputs.image-name }}
    - ${{ inputs.namespace }}
    - ${{ inputs.container-name }}
